#server config
server:
  port: 8761

spring:
  application:
    name: eureka-server #服务名
#Eureka服务注册中心也会将自己作为客户端来尝试注册它自己，所以我们需要禁用它的客户端注册行为。

eureka:
  server:
    enable-self-preservation: false #阻止自我注册
  client:
    fetch-registry: false #获取注册
#    registerWithEureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka #注册中心地址


